### ISSUE TITLE
Neons off are not stored in the vehicle

### ISSUE THREAD

**Issue by fleexcl** [IN1GHTM4R3/qb-carcontrol#3]
When turning off the vehicle's neons from the control menu and then storing the vehicle in a garage, the neon lights are not saved
the vehicle reappears without neon lights, except for stowing the car with the neons activated

**Comment by IN1GHTM4R3** [comment]
neon lights work perfectly in my test server saving in garages you could be missing the function to check for mods on either the in or the out of your garage script.
